services:
  django-gunicorn:
    build: .
    container_name: django-container
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - .:/app
    networks:
      - backend

networks:
  backend: